# Generated by Django 3.1.6 on 2021-02-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('weight', models.FloatField(null=True)),
                ('color', models.CharField(max_length=100, null=True)),
                ('euler_char', models.IntegerField(null=True)),
            ],
        ),
    ]
